import {readFileSync} from 'node:fs';
import {resolve} from 'node:path';
import {act,cleanup,fireEvent,render,screen} from '@testing-library/react';
import {afterEach,beforeAll,beforeEach,expect,it,vi} from 'vitest';
import {activateFrontend} from './runtime';
import {apiRequest} from '../api/client';
import {publishPluginResource} from './events';
import type {FrontendPlugin,PluginContext} from './api';
vi.mock('../api/client',()=>({apiRequest:vi.fn(),setHttpErrorLocalizer:vi.fn()}));
const source=readFileSync(resolve(process.env.VETO_SOURCE_ROOT??'../../IdeaProjects/veto','veto-builtin/src/main/resources/frontend/tasks.js'),'utf8');
let plugin:FrontendPlugin;
beforeAll(async()=>{plugin=await import(/* @vite-ignore */`data:text/javascript;base64,${Buffer.from(source).toString('base64')}`);});
const row={taskId:'bg-1',taskInstanceId:'instance-1',command:'node server.js',cwd:'/work',pid:42,alive:true,exitCode:null,uptimeSeconds:184,recentOutput:'stdout + stderr'};
let items:typeof row[];
const disposers:(()=>void)[]=[];
beforeEach(()=>{items=[{...row}];vi.mocked(apiRequest).mockImplementation(async(_path,options)=>{const request=options?.body as {action:string};if(request.action==='list')return {items,total:items.length,nextOffset:null} as never;items=items[0]?.alive?[{...row,alive:false,exitCode:0 as never}]:[];return {status:'stopped'} as never;});});
afterEach(()=>{cleanup();disposers.splice(0).forEach(dispose=>dispose());vi.resetAllMocks();});
function mount(){const registration=activateFrontend(plugin,{id:'top.focess.builtin:tasks',pluginId:'top.focess.builtin',source,apiVersion:1},'sample','agent',new AbortController().signal);disposers.push(registration.dispose);const Component=registration.inspectors.get('tasks')!.Component;const context:PluginContext={session:'sample',agent:'agent',locale:'en',connected:true,invoke:registration.invoke,subscribe:registration.subscribe};const count=vi.fn();return {...render(<Component context={context} onCount={count}/>),Component,context,count,registration};}
it('preserves merged output, status, uptime and uses immutable identity for stop and remove',async()=>{const view=mount();await screen.findByText('node server.js');expect(screen.getByText('stdout + stderr')).toBeVisible();expect(screen.getByText('3m 4s')).toBeVisible();expect(view.count).toHaveBeenLastCalledWith(1);fireEvent.click(screen.getByRole('button',{name:'Stop'}));await screen.findByText('Exited 0');expect(apiRequest).toHaveBeenCalledWith(expect.any(String),expect.objectContaining({body:expect.objectContaining({action:'stopOrRemove',arguments:{taskId:'bg-1',taskInstanceId:'instance-1'}})}));fireEvent.click(screen.getByRole('button',{name:'Remove'}));await screen.findByText('No background tasks for this session.');});
it('distinguishes loading, failed reads and confirmed empty state',async()=>{let reject!:(value:unknown)=>void;vi.mocked(apiRequest).mockImplementationOnce(()=>new Promise((_resolve,fail)=>{reject=fail;}));mount();expect(screen.getByRole('status')).toHaveTextContent('Loading');await act(async()=>reject(new Error('offline')));expect(screen.getByRole('alert')).toHaveTextContent('temporarily unavailable');expect(screen.queryByText('No background tasks for this session.')).toBeNull();items=[];fireEvent.click(screen.getByRole('button',{name:'Refresh'}));await screen.findByText('No background tasks for this session.');});
it('retains cached output offline, disables writes, localizes and refreshes on reconnect',async()=>{const view=mount();await screen.findByText('Running');view.rerender(<view.Component context={{...view.context,connected:false,locale:'zh-CN'}} onCount={view.count}/>);expect(screen.getByText('stdout + stderr')).toBeVisible();expect(screen.getByRole('button',{name:'停止'})).toBeDisabled();expect(screen.getByText(/连接已断开/)).toBeVisible();items=[{...row,alive:false,exitCode:7 as never}];view.rerender(<view.Component context={{...view.context,locale:'zh-CN'}}/>);await screen.findByText('已退出 7');});
it('rejects stale-instance actions visibly and refreshes without replaying the write',async()=>{const view=mount();await screen.findByText('Running');const original=vi.mocked(apiRequest).getMockImplementation()!;vi.mocked(apiRequest).mockImplementation(async(path,options)=>{if((options?.body as {action:string}).action==='stopOrRemove'){items=[{...row,taskInstanceId:'replacement',command:'new process'}];throw new Error('instance replaced');}return original(path,options);});fireEvent.click(screen.getByRole('button',{name:'Stop'}));await screen.findByText('new process');expect(screen.getByRole('alert')).toHaveTextContent('could not be completed');expect(vi.mocked(apiRequest).mock.calls.filter(([,options])=>(options?.body as {action:string}).action==='stopOrRemove')).toHaveLength(1);view.unmount();const calls=vi.mocked(apiRequest).mock.calls.length;act(()=>publishPluginResource('sample','tasks'));expect(apiRequest).toHaveBeenCalledTimes(calls);});
it('pages task summaries and reads full output with null-safe end cursors',async()=>{vi.mocked(apiRequest).mockImplementation(async(_path,options)=>{const request=options?.body as {action:string;arguments:{offset:number}};return (request.action==='list'?(request.arguments.offset?{items:[{...row,taskId:'bg-2',taskInstanceId:'second',command:'second task'}],total:2,nextOffset:null}:{items:[row],total:2,nextOffset:1}):request.arguments.offset?{text:'tail',total:9,nextOffset:null}:{text:'first',total:9,nextOffset:5}) as never;});const view=mount();await screen.findByText('Running');expect(view.count).toHaveBeenLastCalledWith(2);fireEvent.click(screen.getByRole('button',{name:'Load more'}));await screen.findByText('second task');const detail=screen.getAllByText('Output')[0].closest('details')!;detail.open=true;fireEvent(detail,new Event('toggle'));await screen.findByText('first');fireEvent.click(screen.getByRole('button',{name:'Load more'}));await screen.findByText('firsttail');expect(screen.queryByRole('button',{name:'Load more'})).toBeNull();});
it('clears old scope immediately and aborts list reads on unload',async()=>{const view=mount();await screen.findByText('node server.js');let signal:AbortSignal|undefined;vi.mocked(apiRequest).mockImplementation((_path,options)=>{signal=options?.signal??undefined;return new Promise(()=>{});});view.rerender(<view.Component context={{...view.context,session:'other'}}/>);expect(screen.queryByText('node server.js')).toBeNull();expect(screen.getByRole('status')).toHaveTextContent('Loading');view.unmount();expect(signal?.aborted).toBe(true);});

it('reads truncated metadata separately and resets output pages on invalidation',async()=>{
 let output='original output';
 vi.mocked(apiRequest).mockImplementation(async(_path,options)=>{const request=options?.body as {action:string;arguments:{field?:string}};return (request.action==='list'?{items:[{...row,commandTruncated:true}],total:1,nextOffset:null}:request.action==='detail'?{text:'complete command arguments',total:26,nextOffset:null}:{text:output,total:output.length,nextOffset:null}) as never;});
 mount();await screen.findByText('Running');
 for(const label of ['Full command','Output']){const detail=screen.getByText(label).closest('details')!;detail.open=true;fireEvent(detail,new Event('toggle'));}
 await screen.findByText('complete command arguments');await screen.findByText('original output');
 output='new buffer';act(()=>publishPluginResource('sample','tasks'));await screen.findByText('new buffer');expect(screen.queryByText('original output')).toBeNull();
 expect(apiRequest).toHaveBeenCalledWith(expect.any(String),expect.objectContaining({body:expect.objectContaining({action:'detail',arguments:expect.objectContaining({field:'command',taskInstanceId:'instance-1'})})}));
});
